### ISSUE TITLE
Travis CI - Github

### ISSUE THREAD

**Issue by DavidTorelli** [block-n-roll/blockchain_workshop#15]
This is about integrating Travis CI with this repo.

**Comment by DavidTorelli** [comment]
We need to create an account on Travis CI for this and link into this repo.

**Comment by DavidTorelli** [comment]
Have a look at the projects tab, you can find integration automation also at every column's option (in progress, testing, done, ...)

**Comment by Seryusjj** [comment]
- Added travis CI build support.
- Added simple Junit test case sample to run during build.
- Build status added to readme.md.
Is pending to modify the .travis.yml  after creating the Dockerfile for deployment, but we can close this one.
